### ISSUE TITLE
Korrastada persoonide sugu (PR; analoogia põhjal)

### ISSUE THREAD

**Issue by mitselek** [memoriaal/repis#20]
## Todo
- [x] lisada "N/A" väärtus, kui sugu ei saa määrata;
- [x] kopeerida PR, kus see on võimalik;
- [x] kopeerida analoogia põhjal, kui samanimelised on kõik ühte sugu;
- [ ] #23
- [ ] #21
- [ ] #22

#### Sooga persoone
``` sql
select count(1)
from repis.kirjed k0
where k0.persoon = k0.kirjekood
  and sugu in ("M", "N");
-- 121604
```
#### Soota persoone
``` sql
select count(1)
from repis.kirjed k0
where k0.persoon = k0.kirjekood
  and sugu = "";
-- 55708
```

Päeva lõpuks on jäänud 18651 soota persooni
``` sql
select *
from repis.kirjed k0
where k0.persoon = k0.kirjekood
  and sugu = ""
  and persoon ;
```

**Comment by mitselek** [comment]
Peale manipulatsioone (kui persoonil on kõigi kirjete peale vasturääkivusteta sood, täida sama sooga ka persooni kirje)
``` sql
UPDATE IGNORE repis.kirjed k0
right join
(
  SELECT persoon, GROUP_CONCAT(distinct nullif(Sugu,'')) sugu
  FROM repis.kirjed
  WHERE persoon > 0
  GROUP BY persoon
  HAVING LENGTH(sugu) = 1
) sood 
ON sood.persoon = k0.persoon
SET k0.Sugu = sood.sugu
WHERE k0.persoon = k0.kirjekood
;
```
Lisasin selle protseduuri `maintenance.update_person_sugu()` ka igapäevasesse hooldusskripti.

**Comment by mitselek** [comment]
### Pereregistri sugu kirjetesse
#### Kopeerin Pereregistrist, kui väärtused ei konflikti
``` sql
UPDATE repis.kirjed k0
left join import.pereregister pr on pr.isikukood = k0.kirjekood
set k0.Sugu = 'M'
where pr.isik_sugu = 'mees'
and k0.Sugu != 'N';
/* Affected rows: 9,977  Found rows: 0  Warnings: 0  Duration for 1 query: 6.609 sec. */

UPDATE repis.kirjed k0
left join import.pereregister pr on pr.isikukood = k0.kirjekood
set k0.Sugu = 'N'
where pr.isik_sugu = 'naine'
and k0.Sugu != 'M';
/* Affected rows: 11,422  Found rows: 0  Warnings: 0  Duration for 1 query: 4.438 sec. */
```
#### Kontrollin konflikte
``` sql
select pr.isik_sugu, k0.sugu, k0.*
from repis.kirjed k0
left join import.pereregister pr on pr.isikukood = k0.kirjekood
where pr.isik_sugu = 'mees' and k0.Sugu != 'M'
   or pr.isik_sugu = 'naine' and k0.Sugu != 'N'
;
/* Affected rows: 0  Found rows: 403  Warnings: 0  Duration for 1 query: 1.579 sec. (+ 1.718 sec. network) */
```

**Comment by mitselek** [comment]
Persooni piires konfliktide silumiseks (hetkel 218 persooni) sobib päring:
``` sql
select k.* from repis.kirjed k
right join 
( SELECT persoon, GROUP_CONCAT(distinct nullif(Sugu,'')) sugu
FROM repis.kirjed
WHERE persoon > 0
GROUP BY persoon
HAVING LENGTH(sugu) > 1 ) mn on mn.persoon = k.persoon
;
```
